## NumPy indexing and selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[3]

3

In [5]:
arr[1:4]

array([1, 2, 3])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([5, 6, 7, 8, 9])

In [9]:
 arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [12]:
arr = np.arange(0,10)

In [13]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
half_array = arr[5:]

In [15]:
half_array

array([5, 6, 7, 8, 9])

In [16]:
half_array[:] = 99

In [17]:
half_array

array([99, 99, 99, 99, 99])

In [18]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99])

In [19]:
arr_copy = arr.copy()

In [21]:
arr_copy

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99])

In [22]:
arr_copy[:] = 33

In [23]:
arr_copy

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33])

In [24]:
arr

array([ 0,  1,  2,  3,  4, 99, 99, 99, 99, 99])

In [26]:
arr2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr2d[1][1]

25

In [31]:
 arr2d[1,1]

25

In [32]:
arr2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [41]:
arr2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [44]:
arr2d[1:2, 1:]

array([[25, 30]])

In [45]:
arr3 =np.arange(1,11)

In [46]:
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
bool_arr= arr3 > 5

In [50]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [51]:
arr3[bool_arr]

array([ 6,  7,  8,  9, 10])

In [57]:
arr3[arr3>5]

array([ 6,  7,  8,  9, 10])

In [55]:
arr3[arr3<3]

array([1, 2])

In [58]:
arr_2d = np.arange(50).reshape(5,10)

In [59]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])